### ISSUE TITLE
Circuit browser - UI crashing

### ISSUE THREAD

**Issue by ddelpiano** [VirtualFlyBrain/geppetto-vfb#1138]
Error Information:

Cannot read property 'toString' of undefined

TypeError: Cannot read property 'toString' of undefined
    at locationCypherQuery (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:17:75516)
    at n.value (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:294:686107)
    at n.value (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/main.bundle.js:294:684053)
    at il (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:83371)
    at ds (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:101245)
    at t.unstable_runWithPriority (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:54:3844)
    at Bo (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:45023)
    at ps (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:97717)
    at Zl (https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:93871)
    at https://p2.virtualflybrain.org/org.geppetto.frontend/geppetto/build/common.bundle.js:46:45314

**Comment by jrmartin** [comment]
I committed a fix to feature/1114, https://github.com/VirtualFlyBrain/geppetto-vfb/pull/1132
